// GENERATED by scripts/generate-planned-courses.ts — re-run to refresh stubs.
// Live course: leetcode. Loaded via lib/content/source.ts.
import type { ColorKey } from "@/lib/design/modules";

export type ModuleRecord = {
  id: string;
  slug: string;
  dir: string;
  title: string;
  blurb: string;
  colorKey: ColorKey;
  topicCount: number;
};

export const modules: ModuleRecord[] = [
  {
    id: "01",
    slug: "phase-1",
    dir: "01-phase-1",
    title: "Phase 1",
    blurb: "Fifty foundation problems — arrays, DP warm-ups, graphs, intervals, and lists.",
    colorKey: "cobalt",
    topicCount: 50,
  },
  {
    id: "02",
    slug: "phase-2",
    dir: "02-phase-2",
    title: "Phase 2",
    blurb: "Fifty core-pattern problems — windows, trees, tries, heaps, and design.",
    colorKey: "amber",
    topicCount: 50,
  },
  {
    id: "03",
    slug: "phase-3",
    dir: "03-phase-3",
    title: "Phase 3",
    blurb: "Fifty advanced problems — backtracking, hard graphs, and deep DP.",
    colorKey: "rose",
    topicCount: 50,
  },
];
