// GENERATED by scripts/generate-content.ts — re-run `npm run content:generate`.
// Edits to titles and blurbs are safe; the shape is validated by lib/content/schema.ts.
import type { ColorKey } from "@/lib/design/modules";

export type ModuleRecord = {
  id: string;
  slug: string;
  dir: string;
  title: string;
  blurb: string;
  colorKey: ColorKey;
  topicCount: number;
};

export const modules: ModuleRecord[] = [
  {
    id: "01",
    slug: "foundations",
    dir: "01-foundations",
    title: "Foundations",
    blurb: "Scalability basics, system design process, tradeoffs, and capacity planning.",
    colorKey: "cobalt",
    topicCount: 13,
  },
  {
    id: "02",
    slug: "apis-services-protocols",
    dir: "02-apis-services-protocols",
    title: "APIs, Services & Protocols",
    blurb: "API design, load balancing, gRPC vs REST, retries, and backpressure.",
    colorKey: "amber",
    topicCount: 13,
  },
  {
    id: "03",
    slug: "data-modeling-sql",
    dir: "03-data-modeling-sql",
    title: "Data Modeling & SQL",
    blurb: "Relational database design, indexing, ACID, locking, WAL, and schema evolution.",
    colorKey: "mint",
    topicCount: 13,
  },
  {
    id: "04",
    slug: "nosql-partitioning-ids",
    dir: "04-nosql-partitioning-ids",
    title: "NoSQL, Partitioning & IDs",
    blurb: "NoSQL databases, sharding, consistent hashing, Bloom filters, and ID generation.",
    colorKey: "violet",
    topicCount: 14,
  },
  {
    id: "05",
    slug: "caching-fast-reads",
    dir: "05-caching-fast-reads",
    title: "Caching & Fast Reads",
    blurb: "Caching strategies, eviction policies, Redis, CDN, and cache invalidation.",
    colorKey: "rose",
    topicCount: 7,
  },
  {
    id: "06",
    slug: "distributed-coordination",
    dir: "06-distributed-coordination",
    title: "Distributed Coordination",
    blurb: "Distributed systems foundations, consensus, leader election, gossip protocols.",
    colorKey: "ink",
    topicCount: 13,
  },
  {
    id: "07",
    slug: "storage-engines",
    dir: "07-storage-engines",
    title: "Storage Engines",
    blurb: "LSM trees, B-trees, SSTables, compaction, object storage, and write-ahead logs.",
    colorKey: "teal",
    topicCount: 20,
  },
  {
    id: "08",
    slug: "async-work-streams",
    dir: "08-async-work-streams",
    title: "Async Work & Streams",
    blurb: "Message queues, Kafka, event-driven architecture, task scheduling.",
    colorKey: "lime",
    topicCount: 10,
  },
  {
    id: "09",
    slug: "search-retrieval",
    dir: "09-search-retrieval",
    title: "Search & Retrieval",
    blurb: "Inverted indexes, ranking algorithms, full-text search, autocomplete.",
    colorKey: "orange",
    topicCount: 17,
  },
  {
    id: "10",
    slug: "analytics-sketches",
    dir: "10-analytics-sketches",
    title: "Analytics & Sketches",
    blurb: "Counting at scale, HyperLogLog, streaming analytics, probabilistic data structures.",
    colorKey: "cyan",
    topicCount: 13,
  },
  {
    id: "11",
    slug: "realtime-social-feeds",
    dir: "11-realtime-social-feeds",
    title: "Realtime, Social & Feeds",
    blurb: "WebSockets, news feeds, social graph modeling, push vs pull fanout.",
    colorKey: "fuchsia",
    topicCount: 12,
  },
  {
    id: "12",
    slug: "geo-matching-recs",
    dir: "12-geo-matching-recs",
    title: "Geo, Matching & Recs",
    blurb: "Geospatial indexing, geohash, proximity search, matching algorithms.",
    colorKey: "sky",
    topicCount: 8,
  },
  {
    id: "13",
    slug: "media-files-cdn",
    dir: "13-media-files-cdn",
    title: "Media, Files & CDN",
    blurb: "CDN architecture, video transcoding, file uploads, signed URLs, live streaming.",
    colorKey: "cream",
    topicCount: 11,
  },
  {
    id: "14",
    slug: "reliability-operations",
    dir: "14-reliability-operations",
    title: "Reliability & Operations",
    blurb: "Observability, SLOs, deployment strategies, rate limiting, and incident response.",
    colorKey: "lavender",
    topicCount: 15,
  },
];
