// GENERATED by scripts/generate-planned-courses.ts — re-run to refresh stubs.
// Live course: design-patterns. Loaded via lib/content/source.ts.
import type { ColorKey } from "@/lib/design/modules";

export type ModuleRecord = {
  id: string;
  slug: string;
  dir: string;
  title: string;
  blurb: string;
  colorKey: ColorKey;
  topicCount: number;
};

export const modules: ModuleRecord[] = [
  {
    id: "01",
    slug: "creational",
    dir: "01-creational",
    title: "Creational",
    blurb: "How objects are created when new and constructors are not enough.",
    colorKey: "violet",
    topicCount: 5,
  },
  {
    id: "02",
    slug: "structural",
    dir: "02-structural",
    title: "Structural",
    blurb: "How classes and objects compose into larger structures.",
    colorKey: "cobalt",
    topicCount: 7,
  },
  {
    id: "03",
    slug: "behavioral",
    dir: "03-behavioral",
    title: "Behavioral",
    blurb: "How objects communicate and assign responsibility.",
    colorKey: "teal",
    topicCount: 11,
  },
];
