#!/usr/bin/env tsx
/**
 * One-shot scaffold for planned courses: design-patterns (23 GoF) and
 * leetcode (3 × 50). Skips existing MDX files. Not wired into the live
 * content loader — see content/courses.ts.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function stub(title: string, number: string, extraSummary?: string): string {
  const summary = extraSummary ?? `${title} — notes in progress.`;
  return `---
title: ${JSON.stringify(title)}
number: ${JSON.stringify(number)}
summary: ${JSON.stringify(summary.slice(0, 200))}
status: draft
free: true
difficulty: core
estMinutes: 12
---

## The problem

What breaks without this, and the situation that forces the decision.

## How it works

The mechanism, step by step.

## Tradeoffs

<Tradeoff
  forTitle="Reach for it when"
  againstTitle="Avoid it when"
  forItems={["", ""]}
  againstItems={["", ""]}
/>

## In an interview

How to introduce this, and the follow-up questions it invites.

<KeyTakeaways items={["", "", ""]} />
`;
}

type Topic = { title: string; slug: string; number: string; url?: string };

type ModuleDef = {
  id: string;
  slug: string;
  title: string;
  blurb: string;
  colorKey: string;
  topics: Topic[];
};

function modulesFile(modules: ModuleDef[], courseLabel: string): string {
  const records = modules
    .map(
      (mod) => `  {
    id: "${mod.id}",
    slug: "${mod.slug}",
    dir: "${mod.id}-${mod.slug}",
    title: ${JSON.stringify(mod.title)},
    blurb: ${JSON.stringify(mod.blurb)},
    colorKey: "${mod.colorKey}",
    topicCount: ${mod.topics.length},
  },`,
    )
    .join("\n");

  return `// GENERATED by scripts/generate-planned-courses.ts — re-run to refresh stubs.
// Planned course scaffold for ${courseLabel}. Not loaded by lib/content until live.
import type { ColorKey } from "@/lib/design/modules";

export type ModuleRecord = {
  id: string;
  slug: string;
  dir: string;
  title: string;
  blurb: string;
  colorKey: ColorKey;
  topicCount: number;
};

export const modules: ModuleRecord[] = [
${records}
];
`;
}

function writeCourse(courseSlug: string, modules: ModuleDef[]): { created: number; kept: number } {
  const courseDir = join(ROOT, "content", courseSlug);
  mkdirSync(courseDir, { recursive: true });
  writeFileSync(join(courseDir, "modules.ts"), modulesFile(modules, courseSlug), "utf8");

  let created = 0;
  let kept = 0;
  for (const mod of modules) {
    const dir = join(courseDir, `${mod.id}-${mod.slug}`);
    mkdirSync(dir, { recursive: true });
    for (const topic of mod.topics) {
      const file = join(dir, `${topic.slug}.mdx`);
      if (existsSync(file)) {
        kept++;
        continue;
      }
      const summary = topic.url
        ? `${topic.title} — ${topic.url}`
        : undefined;
      writeFileSync(file, stub(topic.title, topic.number, summary), "utf8");
      created++;
    }
  }
  return { created, kept };
}

function topicsFrom(
  titles: string[],
  moduleId: string,
  urls?: (string | undefined)[],
): Topic[] {
  return titles.map((title, i) => {
    const n = String(i + 1).padStart(2, "0");
    return {
      title,
      slug: slugify(title),
      number: `${moduleId}.${n}`,
      url: urls?.[i],
    };
  });
}

function lc(slug: string): string {
  return `https://leetcode.com/problems/${slug}/`;
}

// --- Design patterns (GoF 23) ------------------------------------------------

const DP_CREATIONAL = [
  "Singleton",
  "Factory Method",
  "Abstract Factory",
  "Builder",
  "Prototype",
];
const DP_STRUCTURAL = [
  "Adapter",
  "Bridge",
  "Composite",
  "Decorator",
  "Facade",
  "Flyweight",
  "Proxy",
];
const DP_BEHAVIORAL = [
  "Chain Of Responsibility",
  "Command",
  "Interpreter",
  "Iterator",
  "Mediator",
  "Memento",
  "Observer",
  "State",
  "Strategy",
  "Template Method",
  "Visitor",
];

function designPatternsModules(): ModuleDef[] {
  return [
    {
      id: "01",
      slug: "creational",
      title: "Creational",
      blurb: "How objects are created when new and constructors are not enough.",
      colorKey: "violet",
      topics: topicsFrom(DP_CREATIONAL, "01"),
    },
    {
      id: "02",
      slug: "structural",
      title: "Structural",
      blurb: "How classes and objects compose into larger structures.",
      colorKey: "cobalt",
      topics: topicsFrom(DP_STRUCTURAL, "02"),
    },
    {
      id: "03",
      slug: "behavioral",
      title: "Behavioral",
      blurb: "How objects communicate and assign responsibility.",
      colorKey: "teal",
      topics: topicsFrom(DP_BEHAVIORAL, "03"),
    },
  ];
}

// --- LeetCode 150 (3 × 50), curated roadmap style ----------------------------
// Seeded as Phase 1 foundations → Phase 2 core patterns → Phase 3 advanced.
// Diff against the Medium roadmap when updating titles/URLs.

type LCItem = { title: string; slug: string };

const PHASE1: LCItem[] = [
  { title: "Two Sum", slug: "two-sum" },
  { title: "Best Time to Buy and Sell Stock", slug: "best-time-to-buy-and-sell-stock" },
  { title: "Contains Duplicate", slug: "contains-duplicate" },
  { title: "Product of Array Except Self", slug: "product-of-array-except-self" },
  { title: "Maximum Subarray", slug: "maximum-subarray" },
  { title: "Maximum Product Subarray", slug: "maximum-product-subarray" },
  { title: "Find Minimum in Rotated Sorted Array", slug: "find-minimum-in-rotated-sorted-array" },
  { title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array" },
  { title: "3Sum", slug: "3sum" },
  { title: "Container With Most Water", slug: "container-with-most-water" },
  { title: "Sum of Two Integers", slug: "sum-of-two-integers" },
  { title: "Number of 1 Bits", slug: "number-of-1-bits" },
  { title: "Counting Bits", slug: "counting-bits" },
  { title: "Missing Number", slug: "missing-number" },
  { title: "Reverse Bits", slug: "reverse-bits" },
  { title: "Climbing Stairs", slug: "climbing-stairs" },
  { title: "Coin Change", slug: "coin-change" },
  { title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence" },
  { title: "Longest Common Subsequence", slug: "longest-common-subsequence" },
  { title: "Word Break", slug: "word-break" },
  { title: "Combination Sum", slug: "combination-sum" },
  { title: "House Robber", slug: "house-robber" },
  { title: "House Robber II", slug: "house-robber-ii" },
  { title: "Decode Ways", slug: "decode-ways" },
  { title: "Unique Paths", slug: "unique-paths" },
  { title: "Jump Game", slug: "jump-game" },
  { title: "Clone Graph", slug: "clone-graph" },
  { title: "Course Schedule", slug: "course-schedule" },
  { title: "Pacific Atlantic Water Flow", slug: "pacific-atlantic-water-flow" },
  { title: "Number of Islands", slug: "number-of-islands" },
  { title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence" },
  { title: "Alien Dictionary", slug: "alien-dictionary" },
  { title: "Graph Valid Tree", slug: "graph-valid-tree" },
  { title: "Number of Connected Components in an Undirected Graph", slug: "number-of-connected-components-in-an-undirected-graph" },
  { title: "Insert Interval", slug: "insert-interval" },
  { title: "Merge Intervals", slug: "merge-intervals" },
  { title: "Non-overlapping Intervals", slug: "non-overlapping-intervals" },
  { title: "Meeting Rooms", slug: "meeting-rooms" },
  { title: "Meeting Rooms II", slug: "meeting-rooms-ii" },
  { title: "Reverse Linked List", slug: "reverse-linked-list" },
  { title: "Detect Cycle in a Linked List", slug: "linked-list-cycle" },
  { title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists" },
  { title: "Merge K Sorted Lists", slug: "merge-k-sorted-lists" },
  { title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list" },
  { title: "Reorder List", slug: "reorder-list" },
  { title: "Set Matrix Zeroes", slug: "set-matrix-zeroes" },
  { title: "Spiral Matrix", slug: "spiral-matrix" },
  { title: "Rotate Image", slug: "rotate-image" },
  { title: "Word Search", slug: "word-search" },
  { title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters" },
];

const PHASE2: LCItem[] = [
  { title: "Longest Repeating Character Replacement", slug: "longest-repeating-character-replacement" },
  { title: "Minimum Window Substring", slug: "minimum-window-substring" },
  { title: "Valid Anagram", slug: "valid-anagram" },
  { title: "Group Anagrams", slug: "group-anagrams" },
  { title: "Valid Parentheses", slug: "valid-parentheses" },
  { title: "Valid Palindrome", slug: "valid-palindrome" },
  { title: "Longest Palindromic Substring", slug: "longest-palindromic-substring" },
  { title: "Palindromic Substrings", slug: "palindromic-substrings" },
  { title: "Encode and Decode Strings", slug: "encode-and-decode-strings" },
  { title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree" },
  { title: "Same Tree", slug: "same-tree" },
  { title: "Invert Binary Tree", slug: "invert-binary-tree" },
  { title: "Binary Tree Maximum Path Sum", slug: "binary-tree-maximum-path-sum" },
  { title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal" },
  { title: "Serialize and Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree" },
  { title: "Subtree of Another Tree", slug: "subtree-of-another-tree" },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", slug: "construct-binary-tree-from-preorder-and-inorder-traversal" },
  { title: "Validate Binary Search Tree", slug: "validate-binary-search-tree" },
  { title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst" },
  { title: "Lowest Common Ancestor of a Binary Search Tree", slug: "lowest-common-ancestor-of-a-binary-search-tree" },
  { title: "Implement Trie Prefix Tree", slug: "implement-trie-prefix-tree" },
  { title: "Design Add and Search Words Data Structure", slug: "design-add-and-search-words-data-structure" },
  { title: "Word Search II", slug: "word-search-ii" },
  { title: "Top K Frequent Elements", slug: "top-k-frequent-elements" },
  { title: "Find Median from Data Stream", slug: "find-median-from-data-stream" },
  { title: "Kth Largest Element in an Array", slug: "kth-largest-element-in-an-array" },
  { title: "Task Scheduler", slug: "task-scheduler" },
  { title: "Design Twitter", slug: "design-twitter" },
  { title: "LRU Cache", slug: "lru-cache" },
  { title: "LFU Cache", slug: "lfu-cache" },
  { title: "Insert Delete GetRandom O(1)", slug: "insert-delete-getrandom-o1" },
  { title: "Time Based Key-Value Store", slug: "time-based-key-value-store" },
  { title: "Snapshot Array", slug: "snapshot-array" },
  { title: "Random Pick with Weight", slug: "random-pick-with-weight" },
  { title: "My Calendar I", slug: "my-calendar-i" },
  { title: "My Calendar II", slug: "my-calendar-ii" },
  { title: "Online Stock Span", slug: "online-stock-span" },
  { title: "Next Greater Element I", slug: "next-greater-element-i" },
  { title: "Daily Temperatures", slug: "daily-temperatures" },
  { title: "Car Fleet", slug: "car-fleet" },
  { title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram" },
  { title: "Binary Search", slug: "binary-search" },
  { title: "Search a 2D Matrix", slug: "search-a-2d-matrix" },
  { title: "Koko Eating Bananas", slug: "koko-eating-bananas" },
  { title: "Find Peak Element", slug: "find-peak-element" },
  { title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays" },
  { title: "Time Needed to Buy Tickets", slug: "time-needed-to-buy-tickets" },
  { title: "Evaluate Reverse Polish Notation", slug: "evaluate-reverse-polish-notation" },
  { title: "Generate Parentheses", slug: "generate-parentheses" },
  { title: "Combination Sum II", slug: "combination-sum-ii" },
];

const PHASE3: LCItem[] = [
  { title: "Permutations", slug: "permutations" },
  { title: "Subsets", slug: "subsets" },
  { title: "Subsets II", slug: "subsets-ii" },
  { title: "Letter Combinations of a Phone Number", slug: "letter-combinations-of-a-phone-number" },
  { title: "Word Break II", slug: "word-break-ii" },
  { title: "Palindrome Partitioning", slug: "palindrome-partitioning" },
  { title: "N-Queens", slug: "n-queens" },
  { title: "Sudoku Solver", slug: "sudoku-solver" },
  { title: "Network Delay Time", slug: "network-delay-time" },
  { title: "Cheapest Flights Within K Stops", slug: "cheapest-flights-within-k-stops" },
  { title: "Min Cost to Connect All Points", slug: "min-cost-to-connect-all-points" },
  { title: "Critical Connections in a Network", slug: "critical-connections-in-a-network" },
  { title: "Swim in Rising Water", slug: "swim-in-rising-water" },
  { title: "Number of Provinces", slug: "number-of-provinces" },
  { title: "Accounts Merge", slug: "accounts-merge" },
  { title: "Redundant Connection", slug: "redundant-connection" },
  { title: "Redundant Connection II", slug: "redundant-connection-ii" },
  { title: "Surrounded Regions", slug: "surrounded-regions" },
  { title: "Walls and Gates", slug: "walls-and-gates" },
  { title: "Rotting Oranges", slug: "rotting-oranges" },
  { title: "Shortest Path in Binary Matrix", slug: "shortest-path-in-binary-matrix" },
  { title: "Word Ladder", slug: "word-ladder" },
  { title: "Word Ladder II", slug: "word-ladder-ii" },
  { title: "Path With Minimum Effort", slug: "path-with-minimum-effort" },
  { title: "Course Schedule II", slug: "course-schedule-ii" },
  { title: "Parallel Courses III", slug: "parallel-courses-iii" },
  { title: "Edit Distance", slug: "edit-distance" },
  { title: "Distinct Subsequences", slug: "distinct-subsequences" },
  { title: "Interleaving String", slug: "interleaving-string" },
  { title: "Burst Balloons", slug: "burst-balloons" },
  { title: "Regular Expression Matching", slug: "regular-expression-matching" },
  { title: "Wildcard Matching", slug: "wildcard-matching" },
  { title: "Maximal Rectangle", slug: "maximal-rectangle" },
  { title: "Trapping Rain Water", slug: "trapping-rain-water" },
  { title: "Trapping Rain Water II", slug: "trapping-rain-water-ii" },
  { title: "Sliding Window Maximum", slug: "sliding-window-maximum" },
  { title: "Minimum Cost For Tickets", slug: "minimum-cost-for-tickets" },
  { title: "Russian Doll Envelopes", slug: "russian-doll-envelopes" },
  { title: "Longest Increasing Path in a Matrix", slug: "longest-increasing-path-in-a-matrix" },
  { title: "Cherry Pickup", slug: "cherry-pickup" },
  { title: "Dungeon Game", slug: "dungeon-game" },
  { title: "Best Time to Buy and Sell Stock III", slug: "best-time-to-buy-and-sell-stock-iii" },
  { title: "Best Time to Buy and Sell Stock IV", slug: "best-time-to-buy-and-sell-stock-iv" },
  { title: "Design File System", slug: "design-file-system" },
  { title: "Sum of Subarray Minimums", slug: "sum-of-subarray-minimums" },
  { title: "Largest BST Subtree", slug: "largest-bst-subtree" },
  { title: "Binary Tree Cameras", slug: "binary-tree-cameras" },
  { title: "Vertical Order Traversal of a Binary Tree", slug: "vertical-order-traversal-of-a-binary-tree" },
  { title: "Count Complete Tree Nodes", slug: "count-complete-tree-nodes" },
  { title: "Merge BSTs to Create Single BST", slug: "merge-bsts-to-create-single-bst" },
];

function phaseModule(
  id: string,
  slug: string,
  title: string,
  blurb: string,
  colorKey: string,
  items: LCItem[],
): ModuleDef {
  if (items.length !== 50) {
    throw new Error(`${title} must have 50 problems, got ${items.length}`);
  }
  return {
    id,
    slug,
    title,
    blurb,
    colorKey,
    topics: items.map((item, i) => {
      const n = String(i + 1).padStart(2, "0");
      return {
        title: item.title,
        slug: slugify(item.title),
        number: `${id}.${n}`,
        url: lc(item.slug),
      };
    }),
  };
}

function leetcodeModules(): ModuleDef[] {
  return [
    phaseModule(
      "01",
      "phase-1",
      "Phase 1",
      "Fifty foundation problems — arrays, DP warm-ups, graphs, intervals, and lists.",
      "cobalt",
      PHASE1,
    ),
    phaseModule(
      "02",
      "phase-2",
      "Phase 2",
      "Fifty core-pattern problems — windows, trees, tries, heaps, and design.",
      "amber",
      PHASE2,
    ),
    phaseModule(
      "03",
      "phase-3",
      "Phase 3",
      "Fifty advanced problems — backtracking, hard graphs, and deep DP.",
      "rose",
      PHASE3,
    ),
  ];
}

function writeSyllabusDp(modules: ModuleDef[]): void {
  const lines = [
    "# Design Patterns syllabus",
    "",
    "Classic Gang of Four patterns, grouped for the planned `design-patterns` course.",
    "",
  ];
  for (const mod of modules) {
    lines.push(`## ${mod.id} ${mod.title}`);
    lines.push("");
    lines.push(mod.blurb);
    lines.push("");
    for (const t of mod.topics) {
      lines.push(`- ${t.number} ${t.title}`);
    }
    lines.push("");
  }
  writeFileSync(join(ROOT, "DesignPatternsSyllabus.md"), lines.join("\n"), "utf8");
}

function writeSyllabusLc(modules: ModuleDef[]): void {
  const lines = [
    "# LeetCode roadmap syllabus",
    "",
    "Curated 150 problems in three phases (50 each), scaffold for the planned `leetcode` course.",
    "Aligned with the Ultimate LeetCode Roadmap structure; diff titles/URLs against the Medium source when updating.",
    "",
    "Source article: https://medium.com/@abhishek-iiit/ultimate-leetcode-roadmap-curated-150-questions-to-crack-0768c78b942b",
    "",
  ];
  for (const mod of modules) {
    lines.push(`## ${mod.id} ${mod.title}`);
    lines.push("");
    lines.push(mod.blurb);
    lines.push("");
    for (const t of mod.topics) {
      lines.push(`- ${t.number} ${t.title}${t.url ? ` — ${t.url}` : ""}`);
    }
    lines.push("");
  }
  writeFileSync(join(ROOT, "LeetCodeSyllabus.md"), lines.join("\n"), "utf8");
}

function main(): void {
  const dp = designPatternsModules();
  const lcMods = leetcodeModules();
  writeSyllabusDp(dp);
  writeSyllabusLc(lcMods);
  const dpStats = writeCourse("design-patterns", dp);
  const lcStats = writeCourse("leetcode", lcMods);
  console.log(
    `design-patterns: ${dpStats.created} created, ${dpStats.kept} kept (${DP_CREATIONAL.length + DP_STRUCTURAL.length + DP_BEHAVIORAL.length} topics)`,
  );
  console.log(
    `leetcode: ${lcStats.created} created, ${lcStats.kept} kept (150 topics)`,
  );
}

main();
