import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  MODULE_COLORS,
  parseSyllabus,
  type ParsedModule,
  type ParsedTopic,
} from "./lib/parse-syllabus";

const ROOT = process.cwd();
const COURSE_DIR = join(ROOT, "content", "system-design");

function moduleDir(mod: ParsedModule): string {
  return join(COURSE_DIR, `${mod.id}-${mod.slug}`);
}

function stub(mod: ParsedModule, topic: ParsedTopic): string {
  // JSON.stringify for both, matching modulesFile() below. Hand-rolling the
  // quote escaping got `title` right and `summary` wrong, so a topic title
  // containing a double quote wrote invalid YAML and the next build failed in
  // gray-matter rather than here.
  return `---
title: ${JSON.stringify(topic.title)}
number: ${JSON.stringify(topic.number)}
summary: ${JSON.stringify(`${topic.title} — notes in progress.`)}
status: draft
free: true
difficulty: core
estMinutes: 12
---

## The problem

What breaks without this, and the situation that forces the decision.

## How it works

The mechanism, step by step.

## Tradeoffs

<Tradeoff
  forTitle="Reach for it when"
  againstTitle="Avoid it when"
  forItems={["", ""]}
  againstItems={["", ""]}
/>

## In an interview

How to introduce this, and the follow-up questions it invites.

<KeyTakeaways items={["", "", ""]} />
`;
}

function modulesFile(modules: ParsedModule[]): string {
  const records = modules
    .map((mod) => {
      const color = MODULE_COLORS[mod.id];
      return `  {
    id: "${mod.id}",
    slug: "${mod.slug}",
    dir: "${mod.id}-${mod.slug}",
    title: ${JSON.stringify(mod.title)},
    blurb: ${JSON.stringify(mod.blurb)},
    colorKey: "${color}",
    topicCount: ${mod.topics.length},
  },`;
    })
    .join("\n");

  return `// GENERATED by scripts/generate-content.ts — re-run \`npm run content:generate\`.
// Edits to titles and blurbs are safe; the shape is validated by lib/content/schema.ts.
import type { ColorKey } from "@/lib/design/modules";

export type ModuleRecord = {
  id: string;
  slug: string;
  dir: string;
  title: string;
  blurb: string;
  colorKey: ColorKey;
  topicCount: number;
};

export const modules: ModuleRecord[] = [
${records}
];
`;
}

function main(): void {
  const parsed = parseSyllabus(readFileSync(join(ROOT, "SDsyllabus.md"), "utf8"));

  if (parsed.modules.length !== 14 || parsed.totalTopics !== 179) {
    throw new Error(
      `refusing to generate: expected 14 modules and 179 topics, got ${parsed.modules.length} and ${parsed.totalTopics}`,
    );
  }

  mkdirSync(COURSE_DIR, { recursive: true });
  writeFileSync(join(COURSE_DIR, "modules.ts"), modulesFile(parsed.modules), "utf8");

  let created = 0;
  let kept = 0;
  for (const mod of parsed.modules) {
    const dir = moduleDir(mod);
    mkdirSync(dir, { recursive: true });
    for (const topic of mod.topics) {
      const file = join(dir, `${topic.slug}.mdx`);
      if (existsSync(file)) {
        kept++;
        continue;
      }
      writeFileSync(file, stub(mod, topic), "utf8");
      created++;
    }
  }

  console.log(
    `modules.ts written · ${created} stub(s) created · ${kept} existing file(s) untouched · ${parsed.totalTopics} topics total`,
  );
}

main();
